---
language:
- python
python:
- '2.7'
install:
- pip install -r ./requirement.txt
before_script:
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
- sleep 5 # give xvfb some time to start
- flake8 ./
- java -jar ./selenium-server-standalone-2.35.0.jar -port 4444 &
- sleep 5 # give SSS some time to start
script:
- nosetests ./ -s -v --nologcapture
